### ISSUE TITLE
How to run the examples?

### ISSUE THREAD

**Issue by erlend-sh** [orhanbalci/rust-steering-behaviors#1]
Hi. I’d love to run these examples, but I’ve never tried to run a Rust program before. Any chance you could describe the fundamental set-up steps, and link to further reading for other Rust fundamentals that might be required in order to understand your instructions?

**Comment by orhanbalci** [comment]
Hi. First of all you should setup rust tooling on your machine. Preferred way of setting up rustc(rust compiler) and cargo (rust package manager) is to use [rustup](https://www.rustup.rs/)  After pulling the project  using git  issue the command :
```
cargo run --example testbehaviors
````

**Comment by erlend-sh** [comment]
Many thanks! I made a quick demonstration:

![ezgif-1-d92ba40989](https://user-images.githubusercontent.com/583842/32414732-c7b6b6e2-c22d-11e7-94f4-a78fa2d3d9ed.gif)

Feel free to put it in the README to demonstrate what the library does. If you want the original .mp4 I can make a PR for it.

**Comment by orhanbalci** [comment]
This is awesome  I was just thinking about this. If you are interested please prepare a PR for this.
